version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "package-lock.json" }}

      - checkout

      - run: npm ci

      - save_cache:
          paths:
            - ./node_modules
          key: pkg-cache-{{ checksum "package-lock.json" }}

      - run: npm test
